/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'content' : string,
  'sender' : Principal,
  'timestamp' : bigint,
}
export interface Clan {
  'members' : Array<Principal>,
  'owner' : Principal,
  'name' : string,
  'totalHeight' : bigint,
}
export interface GlobalStatistics {
  'totalHeightReached' : bigint,
  'totalPlayers' : bigint,
  'totalGamesPlayed' : bigint,
  'totalJumps' : bigint,
}
export interface LeaderboardEntry {
  'principal' : Principal,
  'highestScore' : bigint,
  'prestige' : bigint,
  'level' : bigint,
}
export interface PlayerStats {
  'xp' : bigint,
  'clouds' : bigint,
  'principal' : Principal,
  'highestHeight' : bigint,
  'joinedAt' : bigint,
  'prestige' : bigint,
  'level' : bigint,
}
export interface UserProfile { 'name' : string, 'joinedAt' : bigint }
export interface UserProgress {
  'xp' : bigint,
  'clouds' : bigint,
  'highestHeight' : bigint,
  'prestige' : bigint,
  'level' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createClan' : ActorMethod<[string], undefined>,
  'getCallerClanInfo' : ActorMethod<[], [] | [Clan]>,
  'getCallerProgress' : ActorMethod<[], [] | [UserProgress]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClanInfo' : ActorMethod<[string], [] | [Clan]>,
  'getClanLeaderboard' : ActorMethod<[], Array<Clan>>,
  'getGlobalLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getGlobalStatistics' : ActorMethod<[], GlobalStatistics>,
  'getHighScores' : ActorMethod<[], Array<[string, bigint]>>,
  'getPlayerStats' : ActorMethod<[Principal], [] | [PlayerStats]>,
  'getRecentChatMessages' : ActorMethod<[], Array<ChatMessage>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProgress' : ActorMethod<[Principal], [] | [UserProgress]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinClan' : ActorMethod<[string], undefined>,
  'leaveClan' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendChatMessage' : ActorMethod<[string], undefined>,
  'submitProgress' : ActorMethod<[bigint], undefined>,
  'submitScore' : ActorMethod<[string, bigint], undefined>,
  'updateGlobalStatistics' : ActorMethod<[bigint, bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];