/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Clan = IDL.Record({
  'members' : IDL.Vec(IDL.Principal),
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'totalHeight' : IDL.Nat,
});
export const UserProgress = IDL.Record({
  'xp' : IDL.Nat,
  'clouds' : IDL.Nat,
  'highestHeight' : IDL.Nat,
  'prestige' : IDL.Nat,
  'level' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'joinedAt' : IDL.Int,
});
export const LeaderboardEntry = IDL.Record({
  'principal' : IDL.Principal,
  'highestScore' : IDL.Nat,
  'prestige' : IDL.Nat,
  'level' : IDL.Nat,
});
export const GlobalStatistics = IDL.Record({
  'totalHeightReached' : IDL.Nat,
  'totalPlayers' : IDL.Nat,
  'totalGamesPlayed' : IDL.Nat,
  'totalJumps' : IDL.Nat,
});
export const PlayerStats = IDL.Record({
  'xp' : IDL.Nat,
  'clouds' : IDL.Nat,
  'principal' : IDL.Principal,
  'highestHeight' : IDL.Nat,
  'joinedAt' : IDL.Int,
  'prestige' : IDL.Nat,
  'level' : IDL.Nat,
});
export const ChatMessage = IDL.Record({
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createClan' : IDL.Func([IDL.Text], [], []),
  'getCallerClanInfo' : IDL.Func([], [IDL.Opt(Clan)], ['query']),
  'getCallerProgress' : IDL.Func([], [IDL.Opt(UserProgress)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClanInfo' : IDL.Func([IDL.Text], [IDL.Opt(Clan)], ['query']),
  'getClanLeaderboard' : IDL.Func([], [IDL.Vec(Clan)], ['query']),
  'getGlobalLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getGlobalStatistics' : IDL.Func([], [GlobalStatistics], ['query']),
  'getHighScores' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getPlayerStats' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PlayerStats)],
      ['query'],
    ),
  'getRecentChatMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProgress' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProgress)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinClan' : IDL.Func([IDL.Text], [], []),
  'leaveClan' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendChatMessage' : IDL.Func([IDL.Text], [], []),
  'submitProgress' : IDL.Func([IDL.Nat], [], []),
  'submitScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateGlobalStatistics' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Clan = IDL.Record({
    'members' : IDL.Vec(IDL.Principal),
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'totalHeight' : IDL.Nat,
  });
  const UserProgress = IDL.Record({
    'xp' : IDL.Nat,
    'clouds' : IDL.Nat,
    'highestHeight' : IDL.Nat,
    'prestige' : IDL.Nat,
    'level' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'joinedAt' : IDL.Int });
  const LeaderboardEntry = IDL.Record({
    'principal' : IDL.Principal,
    'highestScore' : IDL.Nat,
    'prestige' : IDL.Nat,
    'level' : IDL.Nat,
  });
  const GlobalStatistics = IDL.Record({
    'totalHeightReached' : IDL.Nat,
    'totalPlayers' : IDL.Nat,
    'totalGamesPlayed' : IDL.Nat,
    'totalJumps' : IDL.Nat,
  });
  const PlayerStats = IDL.Record({
    'xp' : IDL.Nat,
    'clouds' : IDL.Nat,
    'principal' : IDL.Principal,
    'highestHeight' : IDL.Nat,
    'joinedAt' : IDL.Int,
    'prestige' : IDL.Nat,
    'level' : IDL.Nat,
  });
  const ChatMessage = IDL.Record({
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createClan' : IDL.Func([IDL.Text], [], []),
    'getCallerClanInfo' : IDL.Func([], [IDL.Opt(Clan)], ['query']),
    'getCallerProgress' : IDL.Func([], [IDL.Opt(UserProgress)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClanInfo' : IDL.Func([IDL.Text], [IDL.Opt(Clan)], ['query']),
    'getClanLeaderboard' : IDL.Func([], [IDL.Vec(Clan)], ['query']),
    'getGlobalLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getGlobalStatistics' : IDL.Func([], [GlobalStatistics], ['query']),
    'getHighScores' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getPlayerStats' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PlayerStats)],
        ['query'],
      ),
    'getRecentChatMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProgress' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProgress)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinClan' : IDL.Func([IDL.Text], [], []),
    'leaveClan' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendChatMessage' : IDL.Func([IDL.Text], [], []),
    'submitProgress' : IDL.Func([IDL.Nat], [], []),
    'submitScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateGlobalStatistics' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };